version: '3'

services:
  webappconsumer:
    image: webappconsumer:dev
    build:
      args:
        source: obj/Docker/empty/
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webappconsumer$
    volumes:
      - D:\Docker\AdfenixSample\WebAppConsumer\WebAppConsumer:/app
      - C:\Users\Shahriar\vsdbg:/remote_debugger:ro
      #- $nuget_user_folder_webappconsumer$:/root/.nuget/packages:ro
#$nuget_fallback_packages_volume_mapping_webappconsumer$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webappconsumer$ bin/Debug/netcoreapp2.0/WebAppConsumer.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
