version: '3'

services:
  postgresserver:
    image: "postgres"
    restart: always
    environment:
     - POSTGRES_DB:test
     - POSTGRES_USER:test
     - POSTGRES_PASSWORD:test
    ports:
      - 5432:5432    
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
        mynetwork:
          ipv4_address: 172.24.0.2
  webappconsumer:
    image: webappconsumer
    restart: always
    ports:
      - 5001:80
    build:
      context: ./WebAppConsumer
      dockerfile: Dockerfile
    links:
    - postgresserver
    depends_on:
    - postgresserver
    - rabbitmq
    networks:
       mynetwork:
         ipv4_address: 172.24.0.4
  domainpublisherservice:
    image: domainpublisherservice
    restart: always
    build:
      context: ./../DomainPublisherService
      dockerfile: Dockerfile
    depends_on:
    - rabbitmq
    networks:
        mynetwork:
          ipv4_address: 172.24.0.5
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "1567:15672"
    networks:
        mynetwork:
          ipv4_address: 172.24.0.3
volumes:
 pgdata:
networks:
  mynetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 172.24.0.0/16
        


