version: '3'

services:
  postgresserver:
    image: zafrulpostgres
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: zafrul
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
  webappconsumer:
    image: webappconsumer
    ports:
      - 5001:80
    build:
      context: ./WebAppConsumer
      dockerfile: Dockerfile
    links:
    - postgresserver
    depends_on:
    - postgresserver
    - rabbitmq
    networks:
    - mynetwork
  domainpublisherservice:
    image: domainpublisherservice
    build:
      context: ./../DomainPublisherService
      dockerfile: Dockerfile
      depends_on:
      - rabbitmq
  rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
volumes:
     pgdata:
networks:
   mynetwork:
     driver: bridge


