version: '3'

services:
  postgresserver:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test   
    ports:
      - 5432:5432    
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
  webappconsumer:
    image: webappconsumer
    restart: always
    ports:
      - 5001:80
    build:
      context: ./WebAppConsumer
      dockerfile: Dockerfile
    links:
    - postgresserver
    depends_on:
    - postgresserver
    - rabbitmq
    networks:
    - mynetwork
  domainpublisherservice:
    image: domainpublisherservice
    restart: always
    build:
      context: ./../DomainPublisherService
      dockerfile: Dockerfile
    depends_on:
    - rabbitmq
    networks:
    - mynetwork
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "1567:15672"
    networks:
      - mynetwork
volumes:
 pgdata:
networks:
  mynetwork:
    driver: bridge


